<?php

prepare (); //PREPARAR LA CONSULTA

bindParam(); //ENVIAR PARAMETROS A LA CONSULTA

execute (); // EJECUTA LA CONSULTA

fetch() ; // CONVIERTE EN ARRAY UNA CONSULTA 


CALL(); // LLAMA UNA PROCESO ALMACENADO O FUNCION DE MYSQL 


