CREATE DATABASE IF NOT EXISTS SAMADI;
USE SAMADI;
ALTER DATABASE SAMADI DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE IF NOT EXISTS PERSONAS(
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
APELLIDOS VARCHAR (50) NOT NULL,
NOMBRES VARCHAR (50) NOT NULL,
CORREO VARCHAR (50) NOT NULL,
FOTO VARCHAR (25),
PRIMARY KEY (ID),
UNIQUE (CEDULA),
UNIQUE (CORREO)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS CATEDRAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_CATEDRA VARCHAR (10) NOT NULL,
NOMBRE_CATEDRA VARCHAR (150) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_CATEDRA)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS CARRERAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_CARRERA VARCHAR (10) NOT NULL,
NOMBRE_CARRERA VARCHAR (150) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_CARRERA)
)ENGINE = InnoDB COLLATE utf8_unicode_ci; 

CREATE TABLE IF NOT EXISTS NIVELES (
ID INT AUTO_INCREMENT NOT NULL,
COD_NIVEL VARCHAR (10) NOT NULL,
NOMBRE_NIVEL VARCHAR (30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_NIVEL)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS PARALELOS (
ID INT AUTO_INCREMENT NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
NOMBRE_PARALELO VARCHAR (30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (COD_PARALELO)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS JORNADAS (
ID INT AUTO_INCREMENT NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
NOMBRE_JORNADA VARCHAR (30) NOT NULL,
PRIMARY KEY(ID),
UNIQUE (COD_JORNADA)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS ALUMNOS(
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
COD_CARRERA VARCHAR (10) NOT NULL,
COD_NIVEL VARCHAR (10) NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT CEDULA_ALUMNOSYPERSONAS FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT CARRERA_ALUMNOSYCARRERAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA),
CONSTRAINT NIVEL_ALUMNOSYNIVELES FOREIGN KEY (COD_NIVEL) REFERENCES NIVELES (COD_NIVEL),
CONSTRAINT PARALELO_ALUMNOSYPARALELOS FOREIGN KEY (COD_PARALELO) REFERENCES PARALELOS (COD_PARALELO),
CONSTRAINT JORNADA_ALUMNOSYJORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA),
UNIQUE (CEDULA)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS DOCENTES(
ID INT AUTO_INCREMENT NOT NULL,
CEDULA VARCHAR (13) NOT NULL,
COD_CARRERA VARCHAR (10) NOT NULL,
COD_NIVEL VARCHAR (10) NOT NULL,
COD_PARALELO VARCHAR (10) NOT NULL,
COD_JORNADA VARCHAR (10) NOT NULL,
COD_CATEDRA VARCHAR (10) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT CEDULA_DOCENTESYPERSONAS FOREIGN KEY (CEDULA) REFERENCES PERSONAS (CEDULA),
CONSTRAINT CARRERA_DOCENTESYCARRERAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS (COD_CARRERA),
CONSTRAINT NIVEL_DOCENTESYNIVELES FOREIGN KEY (COD_NIVEL) REFERENCES NIVELES (COD_NIVEL),
CONSTRAINT PARALELO_DOCENTESYPARALELOS FOREIGN KEY (COD_PARALELO) REFERENCES PARALELOS (COD_PARALELO),
CONSTRAINT JORNADA_DOCENTESYJORNADA FOREIGN KEY (COD_JORNADA) REFERENCES JORNADAS (COD_JORNADA),
CONSTRAINT CATEDRA_DOCENTESYCATEDRAS FOREIGN KEY (COD_CATEDRA) REFERENCES CATEDRAS (COD_CATEDRA),
UNIQUE (CEDULA)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID INT AUTO_INCREMENT NOT NULL,
USER VARCHAR (150) NOT NULL,
PASSWORD VARCHAR (200) NOT NULL,
TYPE INT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (USER),
CONSTRAINT USER_USUARIOSYPERSONAS FOREIGN KEY (USER) REFERENCES PERSONAS (CORREO)
)ENGINE = InnoDB COLLATE utf8_unicode_ci;

ALTER TABLE SAMADI.ALUMNOS ADD COLUMN TIPO_DISCAPACIDAD TEXT NOT NULL AFTER COD_JORNADA;
ALTER TABLE SAMADI.ALUMNOS ADD COLUMN PORCENTAJE_DISCAPACIDAD FLOAT (3,2) NOT NULL AFTER TIPO_DISCAPACIDAD;